- name: Install Docker and Docker Compose
  become: true
  tags:
    - docker

  block:
    - name: Check if Docker is installed
      ansible.builtin.command: docker --version
      register: docker_check
      ignore_errors: yes
      changed_when: false
      failed_when: false
  
    - name: Install Docker
      when: docker_check.rc != 0
      block:
        - name: update apt cache
          ansible.builtin.apt:
            update_cache: yes
        
        - name: Install dependencies
          ansible.builtin.apt:
            name: 
              - ca-certificates
              - curl
            state: present
        
        - name: Create keyrings directory
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'
        
        - name: Download Docker's GPG key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: '0644'
        
        - name: Set read permissions for Docker GPG key
          ansible.builtin.file:
            path: /etc/apt/keyrings/docker.asc
            mode: 'a+r'
        
        - name: Add Docker repository to apt sources
          ansible.builtin.shell: |
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        - name: Update apt cache after adding repository
          ansible.builtin.apt:
            update_cache: yes
        
        - name: Install Docker packages
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present

        - name: Ensure docker group exists
          ansible.builtin.group:
            name: docker
            state: present
        
        - name: Add user to docker group
          ansible.builtin.user:
            name: "{{ remrob_user }}"
            groups: docker
            append: yes
        
        - name: Start and enable Docker service
          ansible.builtin.service:
            name: docker
            state: started
            enabled: yes